import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, Wrench } from 'lucide-react';
import { useAgentRuns } from '../hooks/useAgentRuns';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { formatRelativeTime } from '../utils/formatters';

export const AgentRunsPage: React.FC = () => {
  const { agentRuns } = useAgentRuns();
  const navigate = useNavigate();

  return (
    <div className="space-y-6 text-left">
      {/* Header Bar */}
      <div className="pb-2 border-b border-[#EAEAEA]">
        <h1 className="text-lg sm:text-xl font-bold text-[#111111] tracking-tight">Agent Runs</h1>
        <p className="text-xs text-[#666666] mt-0.5">Execution logs and autonomous tool calls generated by AgentOS</p>
      </div>

      {/* Agent Runs List */}
      <div className="space-y-3">
        {agentRuns.map((run) => (
          <Card
            key={run.id}
            hoverable
            onClick={() => navigate(`/agent-runs/${run.id.replace('run-', '')}`)}
            className="space-y-3"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <div className="flex items-center gap-3">
                <span className="font-mono text-xs font-bold text-black bg-[#F7F7F7] px-2 py-1 rounded border border-[#EAEAEA]">
                  {run.runNumber}
                </span>
                <h3 className="text-xs sm:text-sm font-semibold text-[#111111]">{run.request}</h3>
              </div>

              <div className="flex items-center gap-2 shrink-0">
                <Badge
                  variant={
                    run.status === 'completed'
                      ? 'success'
                      : run.status === 'running'
                      ? 'info'
                      : 'error'
                  }
                  size="sm"
                >
                  {run.status}
                </Badge>
                <span className="text-[11px] text-[#8A8A8A] font-mono">{run.duration}</span>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pt-2 border-t border-[#EAEAEA] text-[11px] text-[#666666]">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="font-semibold text-[#111111] flex items-center gap-1">
                  <Wrench className="w-3 h-3 text-[#8A8A8A]" /> Tools:
                </span>
                {run.toolsUsed.map((tool, idx) => (
                  <span
                    key={idx}
                    className="bg-[#F7F7F7] px-2 py-0.5 rounded font-mono text-[10px] text-[#111111] border border-[#EAEAEA]"
                  >
                    {tool}
                  </span>
                ))}
              </div>

              <div className="flex items-center gap-3 text-[#8A8A8A]">
                <span>{formatRelativeTime(run.startedAt)}</span>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={(e) => {
                    e.stopPropagation();
                    navigate(`/agent-runs/${run.id.replace('run-', '')}`);
                  }}
                  className="h-6 px-2 text-[10px] text-black hover:underline"
                  rightIcon={<ArrowRight className="w-3 h-3" />}
                >
                  View Details
                </Button>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
};
